<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_anything [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (anything)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ELEMENT anything EMPTY>
	<!ATTLIST anything id NMTOKEN #REQUIRED>
	<!ATTLIST anything expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_tags NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set preload_ahead NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_filter EMPTY>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list,t2_filter)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch false_color NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch min NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch max NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch mres NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="Project"
		unuid="1475258119875.364800810.1138556591"
		mipmaps_folder="trakem2.1475258119875.364800810.1138556591/trakem2.mipmaps/"
		storage_folder=""
		mipmaps_format="0"
	>
	</project>
	<t2_layer_set
		oid="3"
		width="0.0"
		height="0.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top level"
		links=""
		layer_width="2869.0"
		layer_height="6511.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_tags="true"
		paint_edge_confidence_boxes="true"
		prepaint="true"
		preload_ahead="0"
	>
		<t2_calibration
			pixelWidth="1.0"
			pixelHeight="1.0"
			pixelDepth="1.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="pixel"
		/>
		<t2_layer oid="4"
			 thickness="0.0"
			 z="0.0"
			 title=""
		>
			<t2_patch
				oid="5"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.997713,-0.004299,-0.004166,0.983972,1495.280214,5.91175)"
				title="0.0-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_0_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="6"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.997718,-0.004362,-0.004432,0.985539,1494.24887,852.328886)"
				title="0.1-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_1_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="7"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.998157,-0.003668,-0.002388,0.986623,1493.318272,1697.920317)"
				title="0.2-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_2_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="8"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.998234,-0.002456,-0.002922,0.988821,1493.892794,2542.081179)"
				title="0.3-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_3_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="9"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.99841,-0.00187,-0.004323,0.996601,1494.094617,3393.687745)"
				title="0.4-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_4_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="10"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.998882,-0.001082,-0.005995,0.996017,1493.630278,4250.456012)"
				title="0.5-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_5_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="11"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.999294,-3.92E-4,-0.005592,0.999262,1491.628403,5105.555877)"
				title="0.6-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_6_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="12"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.997191,0.002999,-0.006037,0.99862,349.406979,5106.275041)"
				title="0.7-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_7_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="13"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.997184,0.002778,-0.005815,0.995608,351.032322,4252.682926)"
				title="0.8-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_8_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="14"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.997048,0.002009,-0.00514,0.995565,352.413643,3399.54224)"
				title="0.9-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_9_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="15"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.996796,0.00104,-0.003361,0.987735,352.253665,2549.355378)"
				title="0.10-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_10_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="16"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.996456,-8.71E-4,-0.001984,0.984474,350.865399,1704.591128)"
				title="0.11-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_11_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="17"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.996825,-0.003245,-0.004231,0.985138,351.504422,860.951761)"
				title="0.12-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_12_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="18"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.997001,-0.00246,-0.004397,0.983899,352.547171,13.831947)"
				title="0.13-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_13_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="19"
			 thickness="0.0"
			 z="1.0"
			 title=""
		>
			<t2_patch
				oid="20"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.999407,0.033683,-0.026786,0.999516,1377.476564,183.799017)"
				title="1.0-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_0_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="21"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.999835,0.033257,-0.026727,0.992685,1357.465138,1042.049174)"
				title="1.1-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_1_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="22"
				width="1376.0"
				height="1040.0"
				transform="matrix(1.000027,0.032133,-0.024727,0.997746,1337.496602,1893.461461)"
				title="1.2-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_2_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="23"
				width="1376.0"
				height="1040.0"
				transform="matrix(1.000359,0.03089,-0.026214,0.998315,1319.478317,2747.221322)"
				title="1.3-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_3_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="24"
				width="1376.0"
				height="1040.0"
				transform="matrix(1.000239,0.03018,-0.025887,1.002462,1300.125116,3610.305912)"
				title="1.4-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_4_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="25"
				width="1376.0"
				height="1040.0"
				transform="matrix(1.000371,0.029384,-0.025677,1.002175,1280.980119,4473.719799)"
				title="1.5-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_5_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="26"
				width="1376.0"
				height="1040.0"
				transform="matrix(1.000528,0.028558,-0.025687,1.004516,1262.083602,5333.255776)"
				title="1.6-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_6_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="27"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.999492,0.027708,-0.025858,1.004569,118.446417,5305.968496)"
				title="1.7-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_7_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="28"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.999152,0.028211,-0.025265,1.002907,137.416564,4445.863435)"
				title="1.8-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_8_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="29"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.99922,0.028926,-0.025676,1.003537,156.54808,3581.755848)"
				title="1.9-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_9_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="30"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.99957,0.029542,-0.025977,0.999025,175.806349,2725.104572)"
				title="1.10-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_10_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="31"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.999636,0.030251,-0.024318,0.999282,193.323507,1862.658947)"
				title="1.11-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_11_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="32"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.999475,0.031684,-0.026781,0.994404,213.781805,1009.184618)"
				title="1.12-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_12_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="33"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.999255,0.03106,-0.026722,0.998529,234.025689,149.162406)"
				title="1.13-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_13_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="34"
			 thickness="0.0"
			 z="2.0"
			 title=""
		>
			<t2_patch
				oid="35"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.993729,0.048511,-0.04944,0.996502,1427.323882,252.640258)"
				title="2.0-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_0_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="36"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.993999,0.048537,-0.050483,0.992712,1388.597268,1101.200007)"
				title="2.1-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_1_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="37"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.993877,0.048044,-0.04673,0.996978,1347.061203,1961.724677)"
				title="2.2-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_2_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="38"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.993767,0.048163,-0.049358,0.997821,1310.146059,2815.741347)"
				title="2.3-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_3_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="39"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.994411,0.048959,-0.049064,1.002767,1270.400177,3675.059724)"
				title="2.4-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_4_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="40"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.994721,0.049203,-0.050375,1.001873,1231.419553,4533.828072)"
				title="2.5-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_5_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="41"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.994893,0.049445,-0.048765,1.003277,1190.972134,5398.642837)"
				title="2.6-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_6_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="42"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.994623,0.04795,-0.048555,1.003205,50.448249,5348.303422)"
				title="2.7-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_7_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="43"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.99429,0.047814,-0.050542,1.001712,91.120354,4483.625817)"
				title="2.8-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_8_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="44"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.994548,0.047741,-0.049521,1.002179,130.133921,3625.491016)"
				title="2.9-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_9_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="45"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.994574,0.048584,-0.048965,0.997979,169.715556,2764.521766)"
				title="2.10-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_10_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="46"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.994565,0.049104,-0.047145,0.997686,206.628688,1910.224514)"
				title="2.11-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_11_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="47"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.994587,0.049412,-0.050594,0.992779,247.916781,1052.880225)"
				title="2.12-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_12_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="48"
				width="1376.0"
				height="1040.0"